# Generated by Django 4.2.16 on 2024-11-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_orderitem_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupoun_descount",
            field=models.IntegerField(default=0),
        ),
    ]
