# Generated by Django 4.2.16 on 2024-11-05 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_coupoun_descount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="coupoun_descount",
            new_name="coupon_descount",
        ),
    ]
