# Generated by Django 4.2.16 on 2024-11-05 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlistitem",
            old_name="WishList",
            new_name="wishList",
        ),
    ]
