# Generated by Django 4.2.16 on 2024-11-06 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0002_rename_wishlist_wishlistitem_wishlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlistitem",
            old_name="wishList",
            new_name="wishlist",
        ),
    ]
