
name: Keep Render Alive Back -Shop

on:
  schedule:
    - cron: '*/10 * * * *' # Cada 10 minutos (en UTC)

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping /ping endpoint
        run: curl -L -s https://mortshop.onrender.com/ping
